### ISSUE TITLE
update to latest version

### ISSUE THREAD

**Issue by chebro** [pvinis/iosevka-webfont#1]
hey there! could you update the fonts to the latest release (7.0.2 at the time of writing)?

**Comment by pvinis** [comment]
Updating now. Are you using it for anything? I could add it on the readme :)

**Comment by pvinis** [comment]
7.0.2 added!

**Comment by chebro** [comment]
> Updating now. Are you using it for anything? I could add it on the readme :)

Yes! I am using it for my personal website (which is not live yet), thanks for updating the repo ❤️
